version: 0.1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: "0.1.0"
  assembly_file_version: "{version}"
  assembly_informational_version: "0.1.0"

platform: Any CPU

configuration: Release

install:
  - cmd: dotnet restore src\xunit.fixtureintegration.sln

build:
  project: xunit.fixtureintegration.sln
  verbosity: normal
  publish_nuget: true

deploy:
  provider: Environment
  name: NuGet Staging
